services:
  web:
    build: .
    command: python /code/manage.py runserver_plus 0.0.0.0:8000
#    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-g_3rbgqzd4=0d+xfuqppv91^1i994bepsz3gx(e(e=e*xkx4ry"
      - "DJANGO_DEBUG=True"
      - "DJANGO_GITHUB_CLIENT_ID=Ov23litzgiESXaGLWyEj"
      - "DJANGO_GITHUB_SECRET=962c5a6bee394b01a8439e6f2c0c286b176ef01a"
      - "MAIL_RU_APP_PASSWORD=CyFLanbRKbnDWm7vTDMH"
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
